const columns = [
  { name: 'NAME', uid: 'name' },
  { name: 'PHONE NUMBER', uid: 'phoneNumber' },
  { name: 'POSTAL CODE', uid: 'postcode' },
  { name: 'Address Line1', uid: 'addressLine1' },
  { name: 'Address Line2', uid: 'addressLine2' },
  { name: 'CITY', uid: 'city' },
  { name: 'COUNTRY', uid: 'country' },
  { name: 'GOVERNATE', uid: 'governorate' },
  // { name: 'ACTIONS', uid: 'actions' },
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    email: 'tony.reichert@example.com',
    phoneNumber: '555-555-5555',
    addressLine1: 'San Francisco, CA',
    addressLine2: 'aswan, CA',
    city: 'San Francisco',
    postcode: '94108',
    country: 'USA',
    governorate: 'California',
  },
  {
    id: 2,
    name: 'Tony Reichert',
    email: 'tony.reichert@example.com',
    phoneNumber: '555-555-5555',
    addressLine1: 'San Francisco, CA',
    addressLine2: 'aswan, CA',
    city: 'San Francisco',
    postcode: '94108',
    country: 'USA',
    governorate: 'California',
  },
  {
    id: 3,
    name: 'Tony Reichert',
    email: 'tony.reichert@example.com',
    phoneNumber: '555-555-5555',
    addressLine1: 'San Francisco, CA',
    addressLine2: 'aswan, CA',
    city: 'San Francisco',
    postcode: '94108',
    country: 'USA',
    governorate: 'California',
  },
  {
    id: 4,
    name: 'Tony Reichert',
    email: 'tony.reichert@example.com',
    phoneNumber: '555-555-5555',
    addressLine1: 'San Francisco, CA',
    addressLine2: 'aswan, CA',
    city: 'San Francisco',
    postcode: '94108',
    country: 'USA',
    governorate: 'California',
  },
  {
    id: 5,
    name: 'Tony Reichert',
    email: 'tony.reichert@example.com',
    phoneNumber: '555-555-5555',
    addressLine1: 'San Francisco, CA',
    addressLine2: 'aswan, CA',
    city: 'San Francisco',
    postcode: '94108',
    country: 'USA',
    governorate: 'California',
  },
];

export { columns, users };
